"""
Planning mode — structured analysis planning before execution.

Generates a hypothesis-driven plan, then formats it for injection into the
system prompt so the agent can execute step by step.

Two modes:
1. auto_plan=True  — generate a plan and execute immediately (default)
2. auto_plan=False — generate a plan, pause for user confirmation (interactive)
"""
from __future__ import annotations


PLANNING_PROMPT = """Given the following analysis question, create a structured analysis plan.

**Analysis Question:**
{question}

{context_section}

**Requirements:**
Output a JSON analysis plan (no other text, no code-block markers) with this structure:

{{"plan_title": "Brief title",
"hypothesis": ["Hypothesis 1: ...", "Hypothesis 2: ...", "Hypothesis 3: ..."],
"steps": [
  {{"step": 1, "action": "What to do specifically", "tool": "run_sql/search_knowledge_base/discover_tables/...", "why": "What this verifies", "depends_on": null}},
  {{"step": 2, "action": "...", "tool": "...", "why": "...", "depends_on": 1}},
  ...
],
"dimensions_to_check": ["dimension1", "dimension2", ...],
"success_criteria": "Under what conditions can we give a high-confidence conclusion",
"estimated_queries": 8
}}

Planning principles:
- Hypothesis-driven: list hypotheses first, then design steps to test them
- Each step must state what it verifies — avoid vague "look at the data"
- Mark dependencies between steps (earlier results may change direction)
- Estimate the number of queries and keep it reasonable (typically 5-15)
- Prioritise dimensions: causal-chain first, generic second
- When thresholds or boundary conditions are involved (e.g. "more than 3 times",
  "at least 7 days"), spell out whether the SQL should use > or >= to avoid ambiguity"""


def build_planning_prompt(question: str, context: str = "") -> str:
    """Build the prompt that asks the LLM to produce a plan."""
    context_section = ""
    if context:
        context_section = f"**Supplementary context:**\n{context}"

    return PLANNING_PROMPT.format(
        question=question,
        context_section=context_section,
    )


PLAN_INJECTION_TEMPLATE = """## Analysis Plan (generated by Planner)

**Title**: {title}

**Hypotheses**:
{hypotheses}

**Execution Steps**:
{steps}

**Dimensions to Check**: {dimensions}

**Success Criteria**: {success_criteria}

**Estimated Queries**: {estimated_queries}

---
Follow the plan above step by step.  After each step, interpret the result
before deciding whether to continue the plan or adjust direction based on
what you found.  The plan is a guide, not a constraint — if you discover
new leads along the way, feel free to adapt."""


def format_plan_for_injection(plan: dict) -> str:
    """Format a plan dict into text suitable for system-prompt injection."""
    hypotheses = "\n".join(f"- {h}" for h in plan.get("hypothesis", []))

    steps_lines: list[str] = []
    for s in plan.get("steps", []):
        dep = f" (depends on step {s['depends_on']})" if s.get("depends_on") else ""
        steps_lines.append(
            f"{s['step']}. [{s.get('tool', '?')}] {s['action']} — {s['why']}{dep}"
        )
    steps = "\n".join(steps_lines)

    dimensions = ", ".join(plan.get("dimensions_to_check", []))

    return PLAN_INJECTION_TEMPLATE.format(
        title=plan.get("plan_title", "Untitled"),
        hypotheses=hypotheses,
        steps=steps,
        dimensions=dimensions,
        success_criteria=plan.get("success_criteria", ""),
        estimated_queries=plan.get("estimated_queries", "?"),
    )
